#!/bin/bash

# ========================================
# Cloud Shell Quick Setup Script
# Automatically configures project and runs deployment
# ========================================

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║          🚀 Cloud Shell RAG Quick Setup 🚀              ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Get current project from gcloud
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null)

if [ -z "$CURRENT_PROJECT" ] || [ "$CURRENT_PROJECT" = "None" ]; then
    echo -e "${YELLOW}No project is currently set.${NC}"
    echo ""
    echo "Available projects:"
    gcloud projects list --format="table(projectId,name,projectNumber)" 2>/dev/null || true
    echo ""
    echo -n -e "${CYAN}Enter your Project ID: ${NC}"
    read PROJECT_ID
    
    if [ -n "$PROJECT_ID" ]; then
        gcloud config set project "$PROJECT_ID"
        CURRENT_PROJECT="$PROJECT_ID"
        echo -e "${GREEN}✅ Project set to: $PROJECT_ID${NC}"
    else
        echo -e "${YELLOW}No project selected. Exiting.${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}✅ Using project: $CURRENT_PROJECT${NC}"
    echo -n -e "${CYAN}Is this correct? [Y/n]: ${NC}"
    read CONFIRM
    
    if [[ "$CONFIRM" == "n" ]] || [[ "$CONFIRM" == "N" ]]; then
        echo ""
        echo "Available projects:"
        gcloud projects list --format="table(projectId,name,projectNumber)" 2>/dev/null || true
        echo ""
        echo -n -e "${CYAN}Enter your Project ID: ${NC}"
        read PROJECT_ID
        
        if [ -n "$PROJECT_ID" ]; then
            gcloud config set project "$PROJECT_ID"
            CURRENT_PROJECT="$PROJECT_ID"
            echo -e "${GREEN}✅ Project set to: $PROJECT_ID${NC}"
        fi
    fi
fi

# Export for use by other scripts
export GOOGLE_CLOUD_PROJECT="$CURRENT_PROJECT"

# Create or update .env file
echo -e "\n${CYAN}Creating configuration file...${NC}"

cat > .env << EOF
# Auto-generated by Cloud Shell setup
GOOGLE_CLOUD_PROJECT=$CURRENT_PROJECT
GOOGLE_CLOUD_REGION=us-central1
RAG_DEPLOYMENT_MODE=bigquery_enhanced
BIGQUERY_DATASET=rag_unified
BIGQUERY_LOCATION=US
VERTEX_EMBEDDING_MODEL=gemini-embedding-001
VERTEX_GENERATION_MODEL=gemini-2.5-flash
NUM_TEST_DOCS=10
CHUNK_SIZE=1000
CHUNK_OVERLAP=200
ENABLE_HYBRID_SEARCH=true
ENABLE_CACHING=true
ENABLE_RERANKING=true
AUTO_CREATE_RESOURCES=true
AUTO_ENABLE_APIS=true
VERBOSE_LOGGING=true
RUN_TESTS_AFTER_DEPLOY=true
USE_PUBLIC_DATA=false
EOF

echo -e "${GREEN}✅ Configuration created${NC}"

# Enable required APIs
echo -e "\n${CYAN}Enabling required APIs...${NC}"
gcloud services enable aiplatform.googleapis.com --project="$CURRENT_PROJECT" 2>/dev/null || true
gcloud services enable bigquery.googleapis.com --project="$CURRENT_PROJECT" 2>/dev/null || true
gcloud services enable storage.googleapis.com --project="$CURRENT_PROJECT" 2>/dev/null || true
echo -e "${GREEN}✅ APIs enabled${NC}"

# Check if we should run interactive or standard deployment
echo -e "\n${YELLOW}Choose deployment option:${NC}"
echo "  1) Quick deployment with defaults (BigQuery Enhanced RAG)"
echo "  2) Interactive setup (customize all options)"
echo ""
echo -n -e "${CYAN}Select [1-2]: ${NC}"
read CHOICE

if [ "$CHOICE" = "2" ]; then
    echo -e "\n${CYAN}Launching interactive setup...${NC}\n"
    chmod +x deploy_unified_interactive.sh 2>/dev/null || true
    ./deploy_unified_interactive.sh
else
    echo -e "\n${CYAN}Starting quick deployment...${NC}\n"
    chmod +x deploy_unified.sh 2>/dev/null || true
    ./deploy_unified.sh
fi